// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://htahirvnziszdpbepskt.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imh0YWhpcnZuemlzemRwYmVwc2t0Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzU2NTg4OTMsImV4cCI6MjA5MTIzNDg5M30.dO2-g7qSIg1szoLqPAiXKZ5v6skZ4N6h7bcjDwmmSyk";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});